FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/validation/validate.py .
CMD ["python", "validate.py", "s3a://lab6-ecommerce-shop/incoming/orders_*.csv", "s3a://lab6-ecommerce-shop/incoming/order_items_*.csv", "5"]